# Generated by Django 4.2.3 on 2023-07-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='bank',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deposits',
            name='reference',
            field=models.CharField(default='', max_length=255),
        ),
    ]
