# Generated by Django 4.2.3 on 2023-07-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraws',
            name='token',
            field=models.IntegerField(default=0),
        ),
    ]
