# Generated by Django 4.2.3 on 2023-07-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0002_withdraws_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraws',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
